version: '3.7'

services:
  ome:
    build: .
    image: airensoft/ovenmediaengine:latest
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./ome:/opt/ovenmediaengine/bin/origin_conf
      - ./logs/ome:/var/log/ovenmediaengine
  nginx:
    build: .
    image: nginx:latest
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d

    
