version: '3.7'

services:
  ome:
    build: .
    image: airensoft/ovenmediaengine:latest
    restart: unless-stopped
    ports:
    - "1935:1935/tcp"
    - "3333:3333/tcp"
    - "3478:3478/tcp"
    - "10006-10010:10006-10010/udp"
    volumes:
      - ./ome:/opt/ovenmediaengine/bin/origin_conf
      - ./logs/ome:/var/log/ovenmediaengine
  nginx:
    build: .
    image: nginx:latest
    restart: unless-stopped
    ports:
    - "80:80/tcp"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d

    
